"""初始表结构：26张业务表

Revision ID: e8e232332b1d
Revises: 
Create Date: 2026-05-03 09:21:32.095960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8e232332b1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_fund_code_date'), table_name='fund_flows')
    op.drop_table('fund_flows')
    op.drop_index(op.f('idx_recovery_event'), table_name='recovery_plans')
    op.drop_index(op.f('idx_recovery_status'), table_name='recovery_plans')
    op.drop_table('recovery_plans')
    op.drop_table('notification_templates')
    op.drop_table('push_config')
    op.drop_index(op.f('idx_param_change_param'), table_name='param_change_log')
    op.drop_index(op.f('idx_param_change_pending'), table_name='param_change_log', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('idx_param_change_status'), table_name='param_change_log')
    op.drop_table('param_change_log')
    op.drop_index(op.f('idx_macro_type'), table_name='macroeconomic')
    op.drop_table('macroeconomic')
    op.drop_index(op.f('idx_sync_status'), table_name='data_sync_log', postgresql_where="((status)::text = 'failed'::text)")
    op.drop_index(op.f('idx_sync_task'), table_name='data_sync_log')
    op.drop_table('data_sync_log')
    op.drop_index(op.f('idx_layer_consistency'), table_name='layer_outputs', postgresql_where='(is_consistent = false)')
    op.drop_index(op.f('idx_layer_date'), table_name='layer_outputs')
    op.drop_index(op.f('idx_layer_stock'), table_name='layer_outputs')
    op.drop_table('layer_outputs')
    op.drop_index(op.f('idx_feedback_unprocessed'), table_name='experience_feedback', postgresql_where='(is_processed = false)')
    op.drop_table('experience_feedback')
    op.drop_index(op.f('idx_account_sync_type'), table_name='account_sync_log')
    op.drop_table_comment(
        'account_sync_log',
        existing_comment='账户资产同步记录',
        schema=None
    )
    op.alter_column('agent_decisions', 'risk_veto',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_agent_dec_date'), table_name='agent_decisions')
    op.drop_table_comment(
        'agent_decisions',
        existing_comment='最终加权投票决策',
        schema=None
    )
    op.drop_index(op.f('idx_agent_disc_agent'), table_name='agent_discussions')
    op.drop_index(op.f('idx_agent_disc_date_stock'), table_name='agent_discussions')
    op.drop_index(op.f('idx_agent_disc_outcome'), table_name='agent_discussions', postgresql_where='(predicted_outcome IS NOT NULL)')
    op.drop_table_comment(
        'agent_discussions',
        existing_comment='Agent讨论记录',
        schema=None
    )
    op.drop_index(op.f('idx_agent_prompts_active'), table_name='agent_prompts', postgresql_where='(is_active = true)')
    op.drop_table_comment(
        'agent_prompts',
        existing_comment='Agent提示词版本管理',
        schema=None
    )
    op.drop_constraint(op.f('uk_agent_weight'), 'agent_weights', type_='unique')
    op.drop_table_comment(
        'agent_weights',
        existing_comment='Agent权重配置与校准',
        schema=None
    )
    op.drop_index(op.f('idx_backtest_strategy'), table_name='backtest_results')
    op.alter_column('daily_klines', 'adjust_flag',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='复权标志：none=不复权, front=前复权, back=后复权',
               existing_nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.drop_index(op.f('idx_klines_code_date'), table_name='daily_klines')
    op.drop_index(op.f('idx_klines_date'), table_name='daily_klines')
    op.drop_table_comment(
        'daily_klines',
        existing_comment='日K线数据+技术指标，预计600万行/年，按年分区',
        schema=None
    )
    op.alter_column('experiences', 'scenario_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='场景特征哈希=hash(market_state+sector+strategy_type+operation+tags)，用于去重',
               existing_nullable=False)
    op.alter_column('experiences', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='backtest=回测预填充 / real=实盘经验 / rule_extract=统计规则自动提取',
               existing_nullable=False,
               existing_server_default=sa.text("'real'::character varying"))
    op.alter_column('experiences', 'weight',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment=None,
               existing_comment='经验权重，超过6个月降低，3个月未验证归档后设为0',
               existing_nullable=False,
               existing_server_default=sa.text('100.0'))
    op.drop_index(op.f('idx_experiences_active'), table_name='experiences', postgresql_where='((is_archived = false) AND (weight > (0)::numeric))')
    op.drop_index(op.f('idx_experiences_market_state'), table_name='experiences')
    op.drop_index(op.f('idx_experiences_scenario'), table_name='experiences', postgresql_where='(is_archived = false)')
    op.drop_index(op.f('idx_experiences_score'), table_name='experiences', postgresql_where='(is_archived = false)')
    op.drop_index(op.f('idx_experiences_sector'), table_name='experiences')
    op.drop_index(op.f('idx_experiences_source'), table_name='experiences')
    op.drop_index(op.f('idx_experiences_strategy'), table_name='experiences')
    op.drop_table_comment(
        'experiences',
        existing_comment='经验记录',
        schema=None
    )
    op.alter_column('llm_usage', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('llm_usage', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('llm_usage', 'call_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('idx_llm_usage_date'), table_name='llm_usage')
    op.drop_index(op.f('idx_llm_usage_model'), table_name='llm_usage')
    op.drop_table_comment(
        'llm_usage',
        existing_comment='LLM Token用量监控',
        schema=None
    )
    op.drop_index(op.f('idx_market_state_date'), table_name='market_state_log')
    op.drop_table_comment(
        'market_state_log',
        existing_comment='市场状态转换日志，每次状态切换必须记录',
        schema=None
    )
    op.alter_column('news', 'source',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='新闻源标识: cls=财联社, wallstcn=华尔街见闻, gelonghui=格隆汇, jin10=金十, xueqiu=雪球, akshare=AKShare个股新闻',
               existing_nullable=False)
    op.alter_column('news', 'extra',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='各源特有数据，如雪球的{percent:"+2.35%",exchange:"SZ"}, 金十的{important:true,desc:"..."}',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_news_category'), table_name='news')
    op.drop_index(op.f('idx_news_hot'), table_name='news', postgresql_where='(is_hot = true)')
    op.drop_index(op.f('idx_news_published'), table_name='news')
    op.drop_index(op.f('idx_news_related'), table_name='news', postgresql_using='gin')
    op.drop_index(op.f('idx_news_source'), table_name='news')
    op.drop_index(op.f('idx_news_tags'), table_name='news', postgresql_using='gin')
    op.drop_table_comment(
        'news',
        existing_comment='财经新闻数据，复用StockAgent多源采集架构',
        schema=None
    )
    op.drop_index(op.f('idx_notifications_confirm'), table_name='notifications', postgresql_where="((confirm_status)::text = 'pending'::text)")
    op.drop_index(op.f('idx_notifications_dedup'), table_name='notifications', postgresql_where='(dedup_key IS NOT NULL)')
    op.drop_index(op.f('idx_notifications_status'), table_name='notifications', postgresql_where="((push_status)::text = ANY ((ARRAY['pending'::character varying, 'retrying'::character varying])::text[]))")
    op.drop_index(op.f('idx_notifications_type'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_unread'), table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_index(op.f('idx_notifications_user'), table_name='notifications')
    op.drop_table_comment(
        'notifications',
        existing_comment='通知记录',
        schema=None
    )
    op.drop_index(op.f('idx_positions_active'), table_name='positions', postgresql_where='(total_volume > 0)')
    op.drop_index(op.f('idx_positions_cooling'), table_name='positions', postgresql_where='(is_cooling_down = true)')
    op.drop_index(op.f('idx_positions_stock'), table_name='positions')
    op.create_unique_constraint(None, 'positions', ['stock_code'])
    op.create_foreign_key(None, 'positions', 'stocks', ['stock_code'], ['code'])
    op.drop_table_comment(
        'positions',
        existing_comment='持仓管理，推进式仓位分批建仓',
        schema=None
    )
    op.drop_index(op.f('idx_risk_events_date'), table_name='risk_events')
    op.drop_index(op.f('idx_risk_events_level'), table_name='risk_events')
    op.drop_index(op.f('idx_risk_events_recovery'), table_name='risk_events', postgresql_where="((recovery_status)::text <> 'resolved'::text)")
    op.drop_index(op.f('idx_risk_events_type'), table_name='risk_events')
    op.drop_table_comment(
        'risk_events',
        existing_comment='风控事件记录',
        schema=None
    )
    op.drop_index(op.f('idx_risk_metrics_date'), table_name='risk_metrics_daily')
    op.drop_table_comment(
        'risk_metrics_daily',
        existing_comment='每日风控指标快照',
        schema=None
    )
    op.drop_index(op.f('idx_sector_code'), table_name='sector_data')
    op.drop_index(op.f('idx_sector_type_date'), table_name='sector_data')
    op.drop_table_comment(
        'sector_data',
        existing_comment='板块数据（行业/概念/地域），每日更新',
        schema=None
    )
    op.alter_column('sessions', 'access_jti',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Access Token的jti claim，UUID v4',
               existing_nullable=False)
    op.alter_column('sessions', 'refresh_jti',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Refresh Token的jti claim，UUID v4',
               existing_nullable=False)
    op.alter_column('sessions', 'revoked',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE表示会话已撤销（登出/密码修改/新登录踢旧）',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_sessions_access_jti'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_refresh_jti'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_user_active'), table_name='sessions', postgresql_where='(revoked = false)')
    op.drop_constraint(op.f('sessions_user_id_fkey'), 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.drop_table_comment(
        'sessions',
        existing_comment='会话记录表，用于Token黑名单和活跃会话管理',
        schema=None
    )
    op.drop_index(op.f('idx_pool_date'), table_name='stock_pool')
    op.drop_index(op.f('idx_pool_decision'), table_name='stock_pool')
    op.drop_index(op.f('idx_pool_strategy'), table_name='stock_pool')
    op.drop_table_comment(
        'stock_pool',
        existing_comment='每日股票池，记录筛选全流程结果',
        schema=None
    )
    op.drop_index(op.f('idx_stocks_industry'), table_name='stocks')
    op.drop_index(op.f('idx_stocks_st'), table_name='stocks', postgresql_where='(is_st = true)')
    op.drop_index(op.f('idx_stocks_suspended'), table_name='stocks', postgresql_where='(is_suspended = true)')
    op.drop_table_comment(
        'stocks',
        existing_comment='A股基本信息表，约5000行',
        schema=None
    )
    op.drop_index(op.f('idx_stoploss_active'), table_name='stop_loss_conditions', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_stoploss_position'), table_name='stop_loss_conditions')
    op.drop_index(op.f('idx_stoploss_stock'), table_name='stop_loss_conditions')
    op.drop_table_comment(
        'stop_loss_conditions',
        existing_comment='止损条件',
        schema=None
    )
    op.drop_index(op.f('idx_stopprofit_active'), table_name='stop_profit_conditions', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_stopprofit_position'), table_name='stop_profit_conditions')
    op.drop_table_comment(
        'stop_profit_conditions',
        existing_comment='阶梯止盈条件',
        schema=None
    )
    op.drop_table_comment(
        'trade_mode',
        existing_comment='交易模式配置，三态+单向升级',
        schema=None
    )
    op.drop_index(op.f('idx_orders_broker'), table_name='trade_orders', postgresql_where='(broker_order_id IS NOT NULL)')
    op.drop_index(op.f('idx_orders_date'), table_name='trade_orders')
    op.drop_index(op.f('idx_orders_status'), table_name='trade_orders')
    op.drop_index(op.f('idx_orders_stock'), table_name='trade_orders')
    op.drop_table_comment(
        'trade_orders',
        existing_comment='交易订单，全链路记录每笔交易',
        schema=None
    )
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='bcrypt加密密码，cost factor=12',
               existing_nullable=False)
    op.alter_column('users', 'is_initialized',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE表示系统已完成首次设置',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_table_comment(
        'users',
        existing_comment='用户表（单用户系统，仅1行记录）',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        '用户表（单用户系统，仅1行记录）',
        existing_comment=None,
        schema=None
    )
    op.alter_column('users', 'is_initialized',
               existing_type=sa.BOOLEAN(),
               comment='TRUE表示系统已完成首次设置',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               comment='bcrypt加密密码，cost factor=12',
               existing_nullable=False)
    op.create_table_comment(
        'trade_orders',
        '交易订单，全链路记录每笔交易',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_orders_stock'), 'trade_orders', ['stock_code', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_orders_status'), 'trade_orders', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_orders_date'), 'trade_orders', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_orders_broker'), 'trade_orders', ['broker_order_id'], unique=False, postgresql_where='(broker_order_id IS NOT NULL)')
    op.create_table_comment(
        'trade_mode',
        '交易模式配置，三态+单向升级',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'stop_profit_conditions',
        '阶梯止盈条件',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_stopprofit_position'), 'stop_profit_conditions', ['position_id'], unique=False)
    op.create_index(op.f('idx_stopprofit_active'), 'stop_profit_conditions', ['id'], unique=False, postgresql_where='(is_active = true)')
    op.create_table_comment(
        'stop_loss_conditions',
        '止损条件',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_stoploss_stock'), 'stop_loss_conditions', ['stock_code', 'is_active'], unique=False)
    op.create_index(op.f('idx_stoploss_position'), 'stop_loss_conditions', ['position_id'], unique=False)
    op.create_index(op.f('idx_stoploss_active'), 'stop_loss_conditions', ['id'], unique=False, postgresql_where='(is_active = true)')
    op.create_table_comment(
        'stocks',
        'A股基本信息表，约5000行',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_stocks_suspended'), 'stocks', ['is_suspended'], unique=False, postgresql_where='(is_suspended = true)')
    op.create_index(op.f('idx_stocks_st'), 'stocks', ['is_st'], unique=False, postgresql_where='(is_st = true)')
    op.create_index(op.f('idx_stocks_industry'), 'stocks', ['industry'], unique=False)
    op.create_table_comment(
        'stock_pool',
        '每日股票池，记录筛选全流程结果',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_pool_strategy'), 'stock_pool', ['strategy_type', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_pool_decision'), 'stock_pool', ['date', 'final_decision'], unique=False)
    op.create_index(op.f('idx_pool_date'), 'stock_pool', [sa.literal_column('date DESC')], unique=False)
    op.create_table_comment(
        'sessions',
        '会话记录表，用于Token黑名单和活跃会话管理',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key(op.f('sessions_user_id_fkey'), 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_sessions_user_active'), 'sessions', ['user_id'], unique=False, postgresql_where='(revoked = false)')
    op.create_index(op.f('idx_sessions_refresh_jti'), 'sessions', ['refresh_jti'], unique=False)
    op.create_index(op.f('idx_sessions_access_jti'), 'sessions', ['access_jti'], unique=False)
    op.alter_column('sessions', 'revoked',
               existing_type=sa.BOOLEAN(),
               comment='TRUE表示会话已撤销（登出/密码修改/新登录踢旧）',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('sessions', 'refresh_jti',
               existing_type=sa.VARCHAR(length=36),
               comment='Refresh Token的jti claim，UUID v4',
               existing_nullable=False)
    op.alter_column('sessions', 'access_jti',
               existing_type=sa.VARCHAR(length=36),
               comment='Access Token的jti claim，UUID v4',
               existing_nullable=False)
    op.create_table_comment(
        'sector_data',
        '板块数据（行业/概念/地域），每日更新',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_sector_type_date'), 'sector_data', ['sector_type', sa.literal_column('trade_date DESC')], unique=False)
    op.create_index(op.f('idx_sector_code'), 'sector_data', ['sector_code'], unique=False)
    op.create_table_comment(
        'risk_metrics_daily',
        '每日风控指标快照',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_risk_metrics_date'), 'risk_metrics_daily', [sa.literal_column('trade_date DESC')], unique=False)
    op.create_table_comment(
        'risk_events',
        '风控事件记录',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_risk_events_type'), 'risk_events', ['event_type', sa.literal_column('trade_date DESC')], unique=False)
    op.create_index(op.f('idx_risk_events_recovery'), 'risk_events', ['recovery_status', 'recovery_path'], unique=False, postgresql_where="((recovery_status)::text <> 'resolved'::text)")
    op.create_index(op.f('idx_risk_events_level'), 'risk_events', ['event_level', sa.literal_column('trade_date DESC')], unique=False)
    op.create_index(op.f('idx_risk_events_date'), 'risk_events', [sa.literal_column('trade_date DESC')], unique=False)
    op.create_table_comment(
        'positions',
        '持仓管理，推进式仓位分批建仓',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_constraint(None, 'positions', type_='unique')
    op.create_index(op.f('idx_positions_stock'), 'positions', ['stock_code'], unique=False)
    op.create_index(op.f('idx_positions_cooling'), 'positions', ['stock_code'], unique=False, postgresql_where='(is_cooling_down = true)')
    op.create_index(op.f('idx_positions_active'), 'positions', ['id'], unique=False, postgresql_where='(total_volume > 0)')
    op.create_table_comment(
        'notifications',
        '通知记录',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_notifications_user'), 'notifications', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_notifications_unread'), 'notifications', ['user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('idx_notifications_type'), 'notifications', ['event_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_notifications_status'), 'notifications', ['push_status', 'priority'], unique=False, postgresql_where="((push_status)::text = ANY ((ARRAY['pending'::character varying, 'retrying'::character varying])::text[]))")
    op.create_index(op.f('idx_notifications_dedup'), 'notifications', ['dedup_key', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(dedup_key IS NOT NULL)')
    op.create_index(op.f('idx_notifications_confirm'), 'notifications', ['confirm_status', 'expire_at'], unique=False, postgresql_where="((confirm_status)::text = 'pending'::text)")
    op.create_table_comment(
        'news',
        '财经新闻数据，复用StockAgent多源采集架构',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_news_tags'), 'news', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_news_source'), 'news', ['source'], unique=False)
    op.create_index(op.f('idx_news_related'), 'news', ['related_stocks'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_news_published'), 'news', [sa.literal_column('published_at DESC')], unique=False)
    op.create_index(op.f('idx_news_hot'), 'news', ['is_hot', sa.literal_column('hot_score DESC')], unique=False, postgresql_where='(is_hot = true)')
    op.create_index(op.f('idx_news_category'), 'news', ['category'], unique=False)
    op.alter_column('news', 'extra',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='各源特有数据，如雪球的{percent:"+2.35%",exchange:"SZ"}, 金十的{important:true,desc:"..."}',
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('news', 'source',
               existing_type=sa.VARCHAR(length=30),
               comment='新闻源标识: cls=财联社, wallstcn=华尔街见闻, gelonghui=格隆汇, jin10=金十, xueqiu=雪球, akshare=AKShare个股新闻',
               existing_nullable=False)
    op.create_table_comment(
        'market_state_log',
        '市场状态转换日志，每次状态切换必须记录',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_market_state_date'), 'market_state_log', [sa.literal_column('date DESC')], unique=False)
    op.create_table_comment(
        'llm_usage',
        'LLM Token用量监控',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_llm_usage_model'), 'llm_usage', ['model', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_llm_usage_date'), 'llm_usage', [sa.literal_column('date DESC')], unique=False)
    op.alter_column('llm_usage', 'call_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('llm_usage', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('llm_usage', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table_comment(
        'experiences',
        '经验记录',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_experiences_strategy'), 'experiences', ['strategy_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_experiences_source'), 'experiences', ['source', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_experiences_sector'), 'experiences', ['sector', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_experiences_score'), 'experiences', [sa.literal_column('score DESC')], unique=False, postgresql_where='(is_archived = false)')
    op.create_index(op.f('idx_experiences_scenario'), 'experiences', ['scenario_hash'], unique=False, postgresql_where='(is_archived = false)')
    op.create_index(op.f('idx_experiences_market_state'), 'experiences', ['market_state', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_experiences_active'), 'experiences', ['market_state', 'strategy_type', 'is_archived'], unique=False, postgresql_where='((is_archived = false) AND (weight > (0)::numeric))')
    op.alter_column('experiences', 'weight',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment='经验权重，超过6个月降低，3个月未验证归档后设为0',
               existing_nullable=False,
               existing_server_default=sa.text('100.0'))
    op.alter_column('experiences', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='backtest=回测预填充 / real=实盘经验 / rule_extract=统计规则自动提取',
               existing_nullable=False,
               existing_server_default=sa.text("'real'::character varying"))
    op.alter_column('experiences', 'scenario_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='场景特征哈希=hash(market_state+sector+strategy_type+operation+tags)，用于去重',
               existing_nullable=False)
    op.create_table_comment(
        'daily_klines',
        '日K线数据+技术指标，预计600万行/年，按年分区',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_klines_date'), 'daily_klines', [sa.literal_column('trade_date DESC')], unique=False)
    op.create_index(op.f('idx_klines_code_date'), 'daily_klines', ['stock_code', sa.literal_column('trade_date DESC')], unique=False)
    op.alter_column('daily_klines', 'adjust_flag',
               existing_type=sa.VARCHAR(length=10),
               comment='复权标志：none=不复权, front=前复权, back=后复权',
               existing_nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.create_index(op.f('idx_backtest_strategy'), 'backtest_results', ['strategy_type', sa.literal_column('start_date DESC')], unique=False)
    op.create_table_comment(
        'agent_weights',
        'Agent权重配置与校准',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint(op.f('uk_agent_weight'), 'agent_weights', ['agent_name', 'market_state'], postgresql_nulls_not_distinct=False)
    op.create_table_comment(
        'agent_prompts',
        'Agent提示词版本管理',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_agent_prompts_active'), 'agent_prompts', ['agent_name'], unique=False, postgresql_where='(is_active = true)')
    op.create_table_comment(
        'agent_discussions',
        'Agent讨论记录',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_agent_disc_outcome'), 'agent_discussions', ['predicted_outcome', 'actual_outcome'], unique=False, postgresql_where='(predicted_outcome IS NOT NULL)')
    op.create_index(op.f('idx_agent_disc_date_stock'), 'agent_discussions', [sa.literal_column('date DESC'), 'stock_code'], unique=False)
    op.create_index(op.f('idx_agent_disc_agent'), 'agent_discussions', ['agent_name', sa.literal_column('date DESC')], unique=False)
    op.create_table_comment(
        'agent_decisions',
        '最终加权投票决策',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_agent_dec_date'), 'agent_decisions', [sa.literal_column('date DESC')], unique=False)
    op.alter_column('agent_decisions', 'risk_veto',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table_comment(
        'account_sync_log',
        '账户资产同步记录',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_account_sync_type'), 'account_sync_log', ['sync_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('experience_feedback',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('experience_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('feedback_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('suggested_action', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], name=op.f('experience_feedback_experience_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('experience_feedback_pkey'))
    )
    op.create_index(op.f('idx_feedback_unprocessed'), 'experience_feedback', [sa.literal_column('created_at DESC')], unique=False, postgresql_where='(is_processed = false)')
    op.create_table('layer_outputs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('layer_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('stock_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('would_decide', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('final_decided', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_consistent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('layer_outputs_pkey')),
    sa.UniqueConstraint('trade_date', 'layer_name', 'stock_code', name=op.f('layer_outputs_trade_date_layer_name_stock_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='分层回溯验证的各层输出'
    )
    op.create_index(op.f('idx_layer_stock'), 'layer_outputs', ['stock_code', sa.literal_column('trade_date DESC')], unique=False)
    op.create_index(op.f('idx_layer_date'), 'layer_outputs', [sa.literal_column('trade_date DESC')], unique=False)
    op.create_index(op.f('idx_layer_consistency'), 'layer_outputs', ['is_consistent'], unique=False, postgresql_where='(is_consistent = false)')
    op.create_table('data_sync_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('data_source', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('records_affected', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('data_sync_log_pkey')),
    comment='数据同步任务日志，用于质量监控'
    )
    op.create_index(op.f('idx_sync_task'), 'data_sync_log', ['task_name', sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('idx_sync_status'), 'data_sync_log', ['status'], unique=False, postgresql_where="((status)::text = 'failed'::text)")
    op.create_table('macroeconomic',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('indicator_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('indicator_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=30), server_default=sa.text("'akshare'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('macroeconomic_pkey')),
    sa.UniqueConstraint('indicator_type', 'period', name=op.f('macroeconomic_indicator_type_period_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='宏观经济指标，辅助市场状态判断'
    )
    op.create_index(op.f('idx_macro_type'), 'macroeconomic', ['indicator_type'], unique=False)
    op.create_table('param_change_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('strategy_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('param_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('suggestion_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source_experience_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.VARCHAR(length=20), server_default=sa.text("'system_suggest'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('wechat_msg_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('reject_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('backtest_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('backtest_passed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('backtest_detail', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('effective_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('param_change_log_pkey')),
    comment='参数变更审计日志'
    )
    op.create_index(op.f('idx_param_change_status'), 'param_change_log', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_param_change_pending'), 'param_change_log', [sa.literal_column('created_at DESC')], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index(op.f('idx_param_change_param'), 'param_change_log', ['strategy_type', 'param_key', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('push_config',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('push_channel', sa.VARCHAR(length=20), server_default=sa.text("'both'::character varying"), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_start', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('quiet_hours_end', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('push_config_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('push_config_pkey')),
    sa.UniqueConstraint('user_id', 'event_type', name=op.f('push_config_user_id_event_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='推送事件配置'
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('template_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title_template', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('body_template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('json_schema', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('confirm_type', sa.VARCHAR(length=20), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=True),
    sa.Column('confirm_expire_minutes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_templates_pkey')),
    sa.UniqueConstraint('event_type', 'template_name', 'version', name=op.f('notification_templates_event_type_template_name_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='消息推送模板'
    )
    op.create_table('recovery_plans',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('risk_event_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('path_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('agent_diagnosis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('backtest_result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('param_changes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('degraded_mode_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cold_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cold_start_result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['risk_event_id'], ['risk_events.id'], name=op.f('recovery_plans_risk_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recovery_plans_pkey')),
    comment='复苏计划，风控触发后创建'
    )
    op.create_index(op.f('idx_recovery_status'), 'recovery_plans', ['status', 'path_type'], unique=False)
    op.create_index(op.f('idx_recovery_event'), 'recovery_plans', ['risk_event_id'], unique=False)
    op.create_table('fund_flows',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('net_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('main_amount', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('large_order_pct', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('small_order_pct', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('cmf', sa.NUMERIC(precision=10, scale=6), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], name=op.f('fund_flows_stock_code_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('fund_flows_pkey')),
    sa.UniqueConstraint('stock_code', 'trade_date', name=op.f('fund_flows_stock_code_trade_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='资金流向数据（AKShare），用于策略一筛选'
    )
    op.create_index(op.f('idx_fund_code_date'), 'fund_flows', ['stock_code', sa.literal_column('trade_date DESC')], unique=False)
    # ### end Alembic commands ###
